client_name: Harlan Estate
farm_name: Promontory
block_name: 1B
session_name: 1b
test: False
exclude_scans:
include_scans: [2017-09-09_13-28]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-black-green-sep-28-2017-94000.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel