client_name: Larkmead
farm_name: Larkmead Vineyards
block_name: A5a
session_name: a5a
test: False
exclude_scans:
include_scans: [2017-08-30_08-20]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/cluster_june_15_288000.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel