client_name: Dana Estates
farm_name: Lotus
block_name: 5B
session_name: 5b
test: 0
exclude_scans:
include_scans: [2017-08-31_08-52]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-oct-12-2017-86000.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel
