client_name: Harlan Estate
farm_name: Promontory
block_name: 17A
session_name: 17a
test: False
exclude_scans:
include_scans: [2017-09-10_09-18]
role: postprocess
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-oct-29-2017.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel