client_name: Larkmead
farm_name: Larkmead Vineyards
block_name: C8d
session_name: c8d
test: 0
exclude_scans:
include_scans: [2017-08-31_11-46, 2017-08-31_12-45]
role: rvm
detection_params:
        caffemodel_s3_url_cluster: s3://deeplearning_data/models/best/wine-black-green-sep-19-2017-100000.caffemodel
        caffemodel_s3_url_trunk: s3://deeplearning_data/models/best/trunk_june_10_400000.caffemodel
